export const MINICART_OPEN = '@MINICART_OPEN';
export const MINICART_CLOSE = '@MINICART_CLOSE';
export const MINICART_INCREMENT = '@MINICART_INCREMENT';
export const MINICART_DECREMENT = '@MINICART_DECREMENT';
export const MINICART_ADD = '@MINICART_ADD';
export const MINICART_REMOVE = '@MINICART_REMOVE';
